import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const utils = trpc.useContext();
  const items = trpc.useQuery(["items.getAll"]);

  const deleteItem = trpc.useMutation(["items.delete"], {
    onSuccess() {
      utils.invalidateQueries(["items.getAll"]);
    },
  });

  const addNewItem = trpc.useMutation(["items.add"], {
    onSuccess() {
      utils.invalidateQueries(["items.getAll"]);
    },
  });

  const onClickDelete = (id: string) => (e: React.MouseEvent<HTMLElement>) => {
    e.preventDefault();

    deleteItem.mutate({ id });
  };

  const handleSubmit = (e: React.SyntheticEvent) => {
    e.preventDefault();

    addNewItem.mutate({ name });
    setName("");
  };

  const [name, setName] = useState("");

  const handleInputChange = (e: React.FormEvent<HTMLInputElement>) => {
    const {
      currentTarget: { value },
    } = e;

    setName(value);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <form onSubmit={handleSubmit}>
          <h2>Add item:</h2>
          <input
            type="text"
            name="name"
            value={name}
            onChange={handleInputChange}
            className="my-2 w-full border-2 border-black"
          />
          <button
            type="submit"
            className="w-full rounded border-2 p-0 text-center"
          >
            submit
          </button>
        </form>
        <div className="flex flex-col items-center justify-center space-y-2 pt-6 text-2xl text-blue-500">
          {items.data ? (
            items.data.map(({ id, name }) => (
              <div
                key={id}
                className="flex w-full justify-between rounded border-2 border-black px-4"
              >
                <p>{name}</p>
                <button
                  className="w-100 mx-4 rounded"
                  onClick={onClickDelete(id)}
                >
                  x
                </button>
              </div>
            ))
          ) : (
            <p>Loading...</p>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
